### ISSUE TITLE
Test-case label is added to JIRA along with other labels specified in trello

### ISSUE THREAD

**Issue by laurafitzgerald** [aerogear/trira#5]
**What**
Using the tool to transfer cards with labels on them the label `test-case` is also added to each task in JIRA. This requires to be removed manually for tasks that are not `test-case`

**Comment by kpiwko** [comment]
There is a different items saying this should be configurable somehow - #2. I believe would could add a label flag in next version and change behavior of current invocation?

E.g. to preserve current behavior, one would need to add
```
--add-jira-label test-case
```

**Comment by trepel** [comment]
This has been fixed, in version 0.5.0 you can use --add-label parameter to specify comma separated list of labels that will be added to jira tickets. There is not any default label defined anymore.

**Comment by laurafitzgerald** [comment]
@trepel @kpiwko thanks for the change. :D
